[package]
name = "movieland"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
mongodb = "3.3.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
uuid = { version = "1.18.1", features = ["v4"] }
